### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Percimorphism**
Since when Mobius is alive in 1946?

### CODE REVIEW

**Comment by Dicklesworthstone** [comment]
I independent saw the mistake and corrected it before I saw your PR. Sorry
for the confusion

**Comment by Percimorphism** [comment]
wait but it is still not fixed in there.

**Comment by Dicklesworthstone** [comment]
Weird, ok I merged it. Sorry for the confusion

**Comment by Percimorphism** [comment]
other than that. I throughly enjoyed this article. Thanks for this.

**Comment by Dicklesworthstone** [comment]
Very glad you liked it! Thanks

**Pull request merged**
